[flask]
secret_key = "SpayzDajoz"
port = 5005

[image]
backend = "dashscope"
api_url = "https://dashscope-intl.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation"
model = ["wan2.6-image", "wan2.6-image-pro"]
model_edit = ["wan2.6-image"]
# api_version = "2024-02-01"  # only for azure backend

[video]
backend = "dashscope"
api_url = "https://dashscope-intl.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis"
model_image = ["wan2.7-r2v"]
model_text = ["wan2.7-t2v"]
# api_version = "2025-04-01-preview"  # only for azure backend
# azure_path = "openai/deployments/{deployment}/videos/generations"

[sd]
api_url = "http://192.168.0.78:9090"
model = "Juggernaut XL v9"
